services:
  mysql:
    image: mysql:8.0
    container_name: techmister-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: techmister
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - techmister-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  techmister-mysql-data:
